# Generated by Django 4.0.5 on 2022-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=256, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data Nascimento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
        ),
    ]
